# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def BrandSentiment(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SentimentResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="BrandSentiment", llm_response=llm_response, mode="request")
        return typing.cast(types.SentimentResult, result)

    def EvalBrandMatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BrandMatchResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvalBrandMatch", llm_response=llm_response, mode="request")
        return typing.cast(types.BrandMatchResult, result)

    def EvalBrandMatchBatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BrandMatchBatchResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvalBrandMatchBatch", llm_response=llm_response, mode="request")
        return typing.cast(types.BrandMatchBatchResult, result)

    def EvalBrandMatchOllama(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BrandMatchResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvalBrandMatchOllama", llm_response=llm_response, mode="request")
        return typing.cast(types.BrandMatchResult, result)

    def EvalOutput(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.EvalResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvalOutput", llm_response=llm_response, mode="request")
        return typing.cast(types.EvalResult, result)

    def EvalOutputOllama(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.EvalResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvalOutputOllama", llm_response=llm_response, mode="request")
        return typing.cast(types.EvalResult, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, result)

    def RankEntities(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RankingResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RankEntities", llm_response=llm_response, mode="request")
        return typing.cast(types.RankingResult, result)

    def RankEntitiesOllama(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RankingResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RankEntitiesOllama", llm_response=llm_response, mode="request")
        return typing.cast(types.RankingResult, result)

    def RankEntitiesOpenAI(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RankingResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RankEntitiesOpenAI", llm_response=llm_response, mode="request")
        return typing.cast(types.RankingResult, result)

    def RankEntitiesWithSourcesOllama(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RankingResultWithSources:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RankEntitiesWithSourcesOllama", llm_response=llm_response, mode="request")
        return typing.cast(types.RankingResultWithSources, result)

    def RankEntitiesWithSourcesOpenAI(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RankingResultWithSources:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RankEntitiesWithSourcesOpenAI", llm_response=llm_response, mode="request")
        return typing.cast(types.RankingResultWithSources, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def BrandSentiment(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SentimentResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="BrandSentiment", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SentimentResult, result)

    def EvalBrandMatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BrandMatchResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvalBrandMatch", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BrandMatchResult, result)

    def EvalBrandMatchBatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BrandMatchBatchResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvalBrandMatchBatch", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BrandMatchBatchResult, result)

    def EvalBrandMatchOllama(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BrandMatchResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvalBrandMatchOllama", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BrandMatchResult, result)

    def EvalOutput(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.EvalResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvalOutput", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.EvalResult, result)

    def EvalOutputOllama(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.EvalResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvalOutputOllama", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.EvalResult, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, result)

    def RankEntities(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RankingResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RankEntities", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RankingResult, result)

    def RankEntitiesOllama(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RankingResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RankEntitiesOllama", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RankingResult, result)

    def RankEntitiesOpenAI(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RankingResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RankEntitiesOpenAI", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RankingResult, result)

    def RankEntitiesWithSourcesOllama(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RankingResultWithSources:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RankEntitiesWithSourcesOllama", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RankingResultWithSources, result)

    def RankEntitiesWithSourcesOpenAI(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RankingResultWithSources:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RankEntitiesWithSourcesOpenAI", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RankingResultWithSources, result)

    