# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (11)
# #########################################################################

class Answer(BaseModel):
    name: typing.Optional[str] = None
    why: typing.Optional[str] = None

class AnswerWithSources(BaseModel):
    name: typing.Optional[str] = None
    why: typing.Optional[str] = None
    sources: typing.List["Source"]
    confidence: typing.Optional[float] = None

class BrandMatch(BaseModel):
    brand_name: typing.Optional[str] = None
    is_match: typing.Optional[bool] = None
    confidence: typing.Optional[float] = None
    matched_text: typing.Optional[str] = None
    reasoning: typing.Optional[str] = None

class BrandMatchBatchResult(BaseModel):
    matches: typing.List["BrandMatch"]

class BrandMatchResult(BaseModel):
    is_match: typing.Optional[bool] = None
    confidence: typing.Optional[float] = None
    matched_alias: typing.Optional[str] = None
    reasoning: typing.Optional[str] = None

class EvalResult(BaseModel):
    passed: typing.Optional[bool] = None
    score: typing.Optional[float] = None
    feedback: typing.Optional[str] = None
    issues: typing.List[str]

class RankingResult(BaseModel):
    answers: typing.List["Answer"]

class RankingResultWithSources(BaseModel):
    answers: typing.List["AnswerWithSources"]

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class SentimentResult(BaseModel):
    sentiment: typing.Optional[types.Sentiment] = None
    confidence: typing.Optional[float] = None

class Source(BaseModel):
    url: typing.Optional[str] = None
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
