# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class Sentiment(str, Enum):
    Positive = "Positive"
    Neutral = "Neutral"
    Negative = "Negative"

# #########################################################################
# Generated classes (11)
# #########################################################################

class Answer(BaseModel):
    name: str
    why: str

class AnswerWithSources(BaseModel):
    name: str
    why: str
    sources: typing.List["Source"]
    confidence: float

class BrandMatch(BaseModel):
    brand_name: str
    is_match: bool
    confidence: float
    matched_text: typing.Optional[str] = None
    reasoning: str

class BrandMatchBatchResult(BaseModel):
    matches: typing.List["BrandMatch"]

class BrandMatchResult(BaseModel):
    is_match: bool
    confidence: float
    matched_alias: typing.Optional[str] = None
    reasoning: str

class EvalResult(BaseModel):
    passed: bool
    score: float
    feedback: str
    issues: typing.List[str]

class RankingResult(BaseModel):
    answers: typing.List["Answer"]

class RankingResultWithSources(BaseModel):
    answers: typing.List["AnswerWithSources"]

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

class SentimentResult(BaseModel):
    sentiment: Sentiment
    confidence: float

class Source(BaseModel):
    url: str
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
