# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Answer": types.Answer,
    "stream_types.Answer": stream_types.Answer,

    "types.RankingResult": types.RankingResult,
    "stream_types.RankingResult": stream_types.RankingResult,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.SentimentResult": types.SentimentResult,
    "stream_types.SentimentResult": stream_types.SentimentResult,


    "types.Sentiment": types.Sentiment,

}